# Generated by Django 3.0.4 on 2020-04-02 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bucket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='content',
            field=models.CharField(max_length=100, null=True, verbose_name='BUCKET'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER'),
        ),
    ]
