# Generated by Django 3.0.4 on 2020-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0002_auto_20200402_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='content',
            field=models.CharField(max_length=100, null=True, verbose_name='CONTENT'),
        ),
    ]
