# Generated by Django 3.0.4 on 2020-04-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0003_auto_20200403_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucket',
            options={'ordering': ('-create_dt',)},
        ),
    ]
