# Generated by Django 3.0.4 on 2020-04-03 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0002_auto_20200314_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photolog',
            options={'ordering': ('-create_dt', 'name')},
        ),
        migrations.AddField(
            model_name='photolog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photolog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photo.Photolog'),
        ),
    ]
